#!/bin/bash

# WordPress Bootstrap Script for Amazon Linux 2023
# This script is generated by Terraform and run on EC2 instance launch

set -euo pipefail

exec > >(tee /var/log/wordpress-bootstrap.log | logger -t wordpress-bootstrap -s 2>/dev/console) 2>&1

EFS_DNS_NAME="${efs_dns_name}"
SITE_DOMAIN="${site_domain}"
WEB_ROOT="${web_root}"
EFS_MOUNT_POINT="${efs_mount_point}"
SHARED_WP_CONTENT="${shared_wp_content}"
WP_DB_NAME="${wp_db_name}"
WP_DB_USER="${wp_db_user}"
WP_DB_PASSWORD="${wp_db_password}"
WP_DB_HOST="${wp_db_host}"
WORDPRESS_ADMIN_EMAIL="${wordpress_admin_email}"
WORDPRESS_SITE_TITLE="${wordpress_site_title}"

echo "Starting WordPress bootstrap on $(hostname)..."

# Update system packages
dnf update -y
dnf install -y \
	httpd \
	mod_ssl \
	curl \
	tar \
	amazon-efs-utils \
	nfs-utils \
	php8.2 \
	php8.2-cli \
	php8.2-common \
	php8.2-curl \
	php8.2-fpm \
	php8.2-gd \
	php8.2-intl \
	php8.2-mbstring \
	php8.2-mysqlnd \
	php8.2-opcache \
	php8.2-soap \
	php8.2-xml \
	php8.2-zip \
	mariadb105

mkdir -p "$WEB_ROOT"
mkdir -p "$EFS_MOUNT_POINT"

# Mount EFS
if ! grep -q "$EFS_DNS_NAME:/ $EFS_MOUNT_POINT efs" /etc/fstab; then
	echo "$EFS_DNS_NAME:/ $EFS_MOUNT_POINT efs _netdev,tls 0 0" >> /etc/fstab
fi

mount -a

# Wait for EFS to be available
max_attempts=30
attempt=0
while [ $attempt -lt $max_attempts ]; do
	if mountpoint -q "$EFS_MOUNT_POINT"; then
		echo "EFS mounted successfully at $EFS_MOUNT_POINT"
		break
	fi
	attempt=$((attempt + 1))
	echo "Waiting for EFS to mount (attempt $attempt/$max_attempts)..."
	sleep 2
done

if ! mountpoint -q "$EFS_MOUNT_POINT"; then
	echo "ERROR: Failed to mount EFS after $max_attempts attempts"
	exit 1
fi

mkdir -p "$SHARED_WP_CONTENT/uploads"
mkdir -p "$SHARED_WP_CONTENT/plugins"
mkdir -p "$SHARED_WP_CONTENT/themes"

# Download and extract WordPress if not already installed
if [ ! -f "$WEB_ROOT/wp-load.php" ]; then
	echo "Downloading WordPress..."
	curl -fsSL https://wordpress.org/latest.tar.gz -o /tmp/wordpress.tar.gz
	tar -xzf /tmp/wordpress.tar.gz -C /tmp
	cp -a /tmp/wordpress/. "$WEB_ROOT"/
	rm -rf /tmp/wordpress /tmp/wordpress.tar.gz
fi

# Migrate existing wp-content to EFS if needed
if [ -d "$WEB_ROOT/wp-content" ] && [ ! -L "$WEB_ROOT/wp-content" ] && [ -z "$(ls -A "$SHARED_WP_CONTENT")" ]; then
	echo "Migrating existing wp-content to EFS..."
	cp -a "$WEB_ROOT/wp-content"/. "$SHARED_WP_CONTENT"/
fi

# Create symlink to EFS wp-content
rm -rf "$WEB_ROOT/wp-content"
ln -s "$SHARED_WP_CONTENT" "$WEB_ROOT/wp-content"

# Create Apache virtual host configuration
cat > /etc/httpd/conf.d/wordpress.conf <<'HTTPD_EOF'
<VirtualHost *:80>
    ServerName _default_
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php-fpm/www.sock|fcgi://localhost"
    </FilesMatch>

    DirectoryIndex index.php index.html
    ErrorLog /var/log/httpd/wordpress-error.log
    CustomLog /var/log/httpd/wordpress-access.log combined
</VirtualHost>
HTTPD_EOF

# Create wp-config.php if it doesn't exist
if [ ! -f "$WEB_ROOT/wp-config.php" ]; then
	echo "Creating wp-config.php..."
	
	# Fetch authentication salts from WordPress.org
	SALTS="$(curl -fsSL https://api.wordpress.org/secret-key/1.1/salt/ || echo "")"
	
	cat > "$WEB_ROOT/wp-config.php" <<WPCONFIG_EOF
<?php
define( 'DB_NAME', '${WP_DB_NAME}' );
define( 'DB_USER', '${WP_DB_USER}' );
define( 'DB_PASSWORD', '${WP_DB_PASSWORD}' );
define( 'DB_HOST', '${WP_DB_HOST}' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

${SALTS}

\$table_prefix = 'wp_';

define( 'WP_HOME', 'https://${SITE_DOMAIN}' );
define( 'WP_SITEURL', 'https://${SITE_DOMAIN}' );
define( 'FS_METHOD', 'direct' );
define( 'DISABLE_WP_CRON', true );
define( 'WP_MEMORY_LIMIT', '256M' );
define( 'WP_MAX_MEMORY_LIMIT', '512M' );

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
WPCONFIG_EOF
fi

# Create health check endpoint for ALB
cat > "$WEB_ROOT/healthcheck.php" <<'HEALTH_EOF'
<?php
http_response_code(200);
echo 'ok';
EOF

# Set file permissions
usermod -a -G apache ec2-user || true
chown -R apache:apache /var/www "$EFS_MOUNT_POINT"
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;
chown -h apache:apache "$WEB_ROOT/wp-content"

# Enable and start services
systemctl enable php-fpm
systemctl enable httpd
systemctl restart php-fpm
systemctl restart httpd

echo "WordPress bootstrap completed successfully!"
echo "EFS mounted at: $EFS_MOUNT_POINT"
echo "WordPress root: $WEB_ROOT"
echo "Shared content: $SHARED_WP_CONTENT"
echo "Database host: $WP_DB_HOST"
